### ISSUE TITLE
Demo/workshop feedback

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/haddock3-webapp#57]
On 13 Okt a demo/workshop was held to try out the webapp. Gathered feedback:

* [x] Symmetry restraints in emref module (or any array of objects)
  * [x] Plus button is not visible, you need to scroll vertically to see it. Should be visible without scrolling
  * [x] Entering data in one cell made weird change in another cell
  * [x] Would be nice for wide tables to be transposed so first column contains headers.
* [x] Numbered lists should start from 1 not 0. For example molecules in global parameters https://github.com/i-VRESSE/workflow-builder/issues/130
* [x] Make caprieval plots same as ones generated by haddock3-analyse
  * [x] Plots should have gray background
  * [x] Should have suplots with fnat (problem in webapp and cli) https://github.com/haddocking/haddock3/issues/720
* [x] Replace remix favicon with haddock3 one
* [x] Don't show more then 2 decimals
* [x] From subplots link to plot only (for example air_clt.html)
* [ ] If no restraints are given make sure the center of mass restraint is used
* [x] If no clustering is done show individual structures as columns in caprieval table. https://github.com/haddocking/haddock3/issues/719
* [x] If you forget to press save button then you lose all your set values. It would be nice not to have a save button or when you leave a dirty form you are asked for confirmation to discard or save form values.
* [x] #58
* [x] The workflow builder is not styled in same as rest. Caused by styling with tailwind (webapp) vs bootstrap3 (builder).
  * [x] Drag icon is misaligned
  * [x] Navbar shifts

**Comment by sverhoeven** [comment]
* In #51 we switched to loading the plotly spec from the html files generated by haddock3-analyse.
* favicon updated in 5c85486c76a6970037ec64274b5b303c1f8ef9a1

**Comment by sverhoeven** [comment]
@dmijatovic for a good priority list

**Comment by sverhoeven** [comment]
In https://github.com/i-VRESSE/haddock3-webapp/commit/f4c0d930356810dd2d69da4da2bd076c45a7669a a pulldown was added to enlarge a subplot.

**Comment by sverhoeven** [comment]
Start from 1 fixed in https://github.com/i-VRESSE/workflow-builder/pull/136

**Comment by sverhoeven** [comment]
individual structures are shown when no clusters are there. Done in https://github.com/haddocking/haddock3/pull/799

**Comment by sverhoeven** [comment]
Round to 2 decimals is done in https://github.com/haddocking/haddock3/commit/01c0370d43eccd5347ca077cff43120db880a30e
